### ISSUE TITLE
Does this Add-on support configuration.yaml settings for voice effects?

### ISSUE THREAD

**Issue by Digital-Ark** [Poeschl-HomeAssistant-Addons/marytts#1]
I was messing around earlier with a configuration.yaml entry, and could add effects to the voice.

I have since installed an optional voice:
[https://github.com/marytts/voice-cmu-bdl-hsmm/releases/download/v5.2/voice-cmu-bdl-hsmm-5.2.zip](url)

But now when I change effects in the configuration.yaml file, the voice is not updated.

The new voice and voice effects all work in the Web UI.  I just can't figure out how to make them apply to the output.

I got the example configuration file here:
[https://www.home-assistant.io/integrations/marytts](url)

It looks like this:
```
tts:
  - platform: marytts
    host: "localhost"
    port: 59125
    codec: "WAVE_FILE"
    voice: "cmu-bdl-hsmm"
    language: "en_US"
    effect:
      Volume: "amount:2.0;"
      TractScaler: "amount:1.5;"
      F0Scale: "f0Scale:2.0;"
      F0Add: "f0Add:50.0;"
      Rate: "durScale:1.5;"
      Robot: "amount:100.0;"
      Whisper: "amount:100.0;"
      Stadium: "amount:100.0"
      Chorus: "delay1:466;amp1:0.54;delay2:600;amp2:-0.10;delay3:250;amp3:0.30"
      FIRFilter: "type:3;fc1:500.0;fc2:2000.0"
      JetPilot: ""
```
